name: iOS Build & Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-14        # Runner Apple Silicon con Xcode preinstalado
    steps:
      - uses: actions/checkout@v4

      # Selecciona la versión de Xcode que ya existe en el runner
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'   # ajusta a la que quieras; 'latest-stable' también funciona

      # Compila y lanza los tests en un simulador
      - name: Build & Test
        run: |
          xcodebuild test \
            -scheme AyusoConMorty \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -resultBundlePath TestResults \
            | xcpretty -c

      # Sube los resultados (opcional, útil en la UI de GitHub)
      - uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults

