name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-14        # Runner con Xcode 16 pre-instalado
    steps:
      - uses: actions/checkout@v4

      # Selecciona la versión exacta de Xcode que quieres (ajusta si cambia)
      - name: Select Xcode 16
        run: sudo xcode-select -s "/Applications/Xcode_16.0.app"

      # (Opcional) Caché de SwiftPM para acelerar
      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

      # Compila + tests en simulador
      - name: Build & Test
        run: |
          xcodebuild test \
            -scheme AyusoConMorty \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
            -resultBundlePath TestResults \
            | xcpretty -c
      # Sube los resultados para inspección en la UI de GitHub
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults

  build-ipa:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16
        run: sudo xcode-select -s "/Applications/Xcode_16.0.app"

      # Genera el .xcarchive en modo Release
      - name: Archive
        run: |
          xcodebuild \
            -scheme AyusoConMorty \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/AyusoConMorty.xcarchive \
            archive

      # Exporta el IPA usando tu ExportOptions.plist
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/AyusoConMorty.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build/ipa

      # Lo dejamos como artefacto para descargar
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: AyusoConMorty-IPA
          path: build/ipa/*.ipa

